
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-them="light"
      className={` ${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white">
        <Navbar></Navbar>
        {children}
         <Footer></Footer>
         
        </body>
    </html>
  );
}
